# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new betaDebug build to fir"
  lane :MEINV do
    # add actions here: https://docs.fastlane.tools/actions
    build_app(
            workspace: "MEINV.xcworkspace",
            scheme:"MEINV",
            export_method:"ad-hoc",
            output_directory:"./fastlane/package",
            configuration:"Release",
            export_xcargs: "-allowProvisioningUpdates"

)
            

    firim(firim_api_token:"e60d240513268821d50ed7ebc7e99e99")
  end
end
